# Generated by Django 4.2.5 on 2023-09-27 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_owner_lesson_owner'),
        ('users', '0003_user_role_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='статус подписки')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='курс', to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='подписчик', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'подписчик',
                'verbose_name_plural': 'подписчики',
            },
        ),
    ]
